name: "Tests on push"
on:
  push:
    branches:
      - '*'

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests ubuntu
        run: pwd && python3 -m unittest
  run_tests_windows:
    runs-on: windows-latest
    steps:
      - name: Run tests windows
        run: python -m unittest
